sudo: required
services:
  - docker
before_install:
  - docker build -t desmonduz/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true desmonduz/docker-react npm run test
language: generic